### ISSUE TITLE
segfault

### ISSUE THREAD

**Issue by marilmanen** [eteran/nedit-ng#105]
This was my second crash and I have no idea how these should be handled.
Here is a line from /var/log/messages

    nedit-ng[1789]: segfault at 4112d70f ip 000000000058b903 sp 00007ffc5de9ffe8 error 4 in nedit-ng[400000+264000]

At the time of the crash I was not doing anything with the editor.

**Comment by eteran** [comment]
Hmm, unfortunately, there's not an awful lot that I can glean from that message. But I'll keep an eye out for crashes. I haven't experienced any with current code bases for a while though.

**Comment by eteran** [comment]
I am closing this, not because it isn't an issue, but because there is really not enough to go on. The faulting address is specific to the binary that was compiled on your system, so it has no relationship to any binary I might have.

if you observe any crashes in the future, please report, and please do with as much information as possible.

Thanks!
