### ISSUE TITLE
goto_line_number() not following focus_window() command

### ISSUE THREAD

**Issue by marilmanen** [eteran/nedit-ng#114]
Here is an example macro (executed in opened LICENSE.md file). It goes to line 10 in LICENSE.md file and not in README.md as I would expect.

```
open($file_path "README.md")
focus_window($file_path "README.md")
goto_line_number(10)
```

The $file_path is required even if the macro is executed from a tab which contains LICENSE.md. My editor was started in a different directory, so it looks like open() command does not use current file directory as a base directory. I think this part is related to issue #92

**Comment by eteran** [comment]
OK, I'll check it out

**Comment by eteran** [comment]
So, today and tomorrow are moving days for me, but rest assured that I will work on fixes. Thank you so much for identifying all of these little details!

**Comment by eteran** [comment]
easy fix :-)

macro functions were set to affect the document which launched the macro, not the one which has the current focus.

**Comment by marilmanen** [comment]
Here is a modified example macro which still has an issue with the cursor location. Correct line of the file is selected, but cursor remains in old location and if the given line number is not in the visible area of the file, it will remain in the "hidden" area. This happens only when file is opened or when tab is changed. Inside the Readme.md tab the cursor and selection behaves correctly. Old NEdit does not have this issue.

number = 1
while ( number > 0 ) {
  number = string_dialog("Give line number to go")
  open($file_path "README.md")
  focus_window($file_path "README.md")
  goto_line_number(number)
}

**Comment by eteran** [comment]
OK, looking into that too, LOL

**Comment by eteran** [comment]
Hmm, so this and all related are all related to a particular quirk in nedit/nedit-ng's design that I need to work out.

Basically, it manually tracks the focus when you switch documents, this seems to be necessary because when we have a split view, we need to know which part of the split to whatever change was requested to... but Qt in some cases delivers events in a different order than Motif did... so sometimes it will try to do some work BEFORE the focus change event has occured :-/

I need to develop a better solution overall, which should help with this and any similar issues.

**Comment by eteran** [comment]
I believe that this issue is fixed in master. I am still working on a more generalized, elegant solution than the manual focus tracking because when a macro (or menu item) wants to do work in a text area, it needs to figure out which one the user means. Which can get complicated when things like splitters are involved.

Please re-open if the problem persists!
