### ISSUE TITLE
Learn/replay option in "repeat..." is always deactivated (Windows 10)

### ISSUE THREAD

**Issue by aks2161989** [eteran/nedit-ng#162]
The learn/replay button in "repeat..." option is always deactivated (even after recording a macro). I am on Windows 10.

**Comment by eteran** [comment]
Interesting, I'll have to look into it. Thanks!

**Comment by eteran** [comment]
Whoops, there a typo in the commit message there, sorry **this** issue is still open.

**Comment by eteran** [comment]
I think that this is fixed and was the same as issue #189 !

Please re-open if you still have the issue.

**Comment by grege2** [comment]
Hi Evan @eteran,

I think this issue is still there unfortunately, on Mac Catalina 10.15.7 and Mojave 10.14.6.  I was just about to report the same. My Repeat Dialog always has the Learn/Replay option greyed out, no matter what I have done with Learn / Replay / keystrokes etc.

I've had a hunt around in the code. I can see DialogRepeat gets set up with `ui.setupUi(this)` in `DialogRepeat::DialogRepeat()`. In DialogRepeat.ui the button is initalized to disabled ..

```
      <widget class="QRadioButton" name="radioLearnReplay">
        <property name="enabled">
         <bool>false</bool>
        </property>
```
I can't see anywhere that the radio button is enabled, after a keystroke macro has been recorded. It feels like `replayMacro.isEmpty()` should get checked and enable the button. So I have put this ..
```
   const QString replayMacro = CommandRecorder::instance()->replayMacro();
   if (!replayMacro.isEmpty()) ui.radioLearnReplay->setEnabled(true);
```
at the bottom of DialogRepeat::DialogRepeat(DocumentWidget *document, QWidget *parent, Qt::WindowFlags f) and Voila ! ca marche !

For clarity, this is the complete function ..
```
DialogRepeat::DialogRepeat(DocumentWidget *document, QWidget *parent, Qt::WindowFlags f)
	: Dialog(parent, f), document_(document) {

	ui.setupUi(this);
	connectSlots();

	QTimer::singleShot(0, this, [this]() {
		resize(0, 0);
	});

	ui.lineEdit->setValidator(new QIntValidator(0, INT_MAX, this));
   
        const QString replayMacro = CommandRecorder::instance()->replayMacro();  // grege2
        if (!replayMacro.isEmpty()) ui.radioLearnReplay->setEnabled(true);       // grege2
}
```
There's probably a better way to do it. Anyway, see what you think. Cheers.

**Comment by eteran** [comment]
Thanks for this, I'll take a look. I think the original bug report was regarding the menu items and your new report has to do with the dialog. But still, good find. I'll investigate!

**Comment by eteran** [comment]
Holy cow, how did I miss this one. Looking at nedit-5.6... it has essentally the exact logic you describe:

```
    XtVaCreateManagedWidget("learnReplayToggle",
    	    xmToggleButtonWidgetClass, radioBox, XmNset, False,
	    XmNlabelString,
	    	s1=XmStringCreateSimple("Learn/Replay"),
	    XmNmnemonic, 'L',
	    XmNsensitive, ReplayMacro != NULL, NULL);
```

That last line is saying "enable it if `ReplayMacro` isn't `NULL`. Easy fix, good catch!

**Comment by eteran** [comment]
@grege2 Fixed in master, thanks :-D

**Comment by grege2** [comment]
Great. I use "Repeat" of the Learn/Replay macro quite a lot. Solved !
