### ISSUE TITLE
very large file not opened correctly and crashing when searching text (Support files > 4GB by using 64-bit code everywhere)

### ISSUE THREAD

**Issue by marilmanen** [eteran/nedit-ng#164]
This is just a note of difference between Nedit and Nedit-ng.

Nedit: Opening a 8.8G file gives an error message "File size 8Gbytes is too large to edit" 
Nedit-ng: Opens the file, but  shows only 8043827 first lines and crashes when using search if the string is found outside the visible lines.

**Comment by eteran** [comment]
Right, so there are some real hard to overcome hurdles with getting to being "purely" 64-bit in nedit's support. The biggest is that Qt's scrollbars are 32-bit.

Because of that, some other things have internally remained 32-bit.

I'd like to get to full 64-bit support... but at least for now, nedit-ng still only supports files up to 4GB per editor tab.

Thank you for filing this issue though, it will be good for tracking the last bits of 64-bit support.

**Comment by eteran** [comment]
The crash is interesting though... I'll have to look into it.

**Comment by eteran** [comment]
So, I haven't been able to get it to crash. But I'll definitely add a message for dealing with files too large to open.

I definitely want to get "real" 64-bit support in there, but it is a challenge due to the previously mentioned Scrollbar issue.

Basically, the scrollbars take 32-bit ints for the min/max/value. I could make a custom scrollbar... but I don't place them manually! I use a "QAbstractScrollArea"... so I'd need to reimplement that too :-P.

It gets messy a little quickly.

But... I'll see what I can do!

**Comment by eteran** [comment]
The latest in master should now disallow you from opening a file > 4GB in size. I'm exploring how to best lift that limit, it's gonna be complicated but definitely doable.

Basically will need to make entirely custom scrollbars, so it may take a bit.

**Comment by eteran** [comment]
technically "fixed", but true support for files > 4GB will take some more doing.

**Comment by grege2** [comment]
Hi all, I did a bit of destruction testing on my new Mac Catalina nedit-ng. It seems to load files ok up to 2GB. Eg. file size 2,139,989,040 bytes is ok but 2,234,937,792 is not. No. of lines was 44,131,686 which displayed ok in the line numbers panel. Load time about 9 seconds. Scrolled around pretty well, very useable. Search time to find a unique word in the middle of the file about 4 seconds. Made a change and saved, save time about 7 seconds. I'm happy with that. Not that I intend to edit 2 GB files with 44 million lines very often. A six year-old MB Pro with 16GB memory and a SSD drive, the exercise didn't appear to challenge it much, all stats very calm, CPU, mem, Disk etc. 

```
#/tmp $ wc big6
 44131686 127383620 2139989040 big6
#/tmp $ ls -l big6
-rw-r--r--  1 gedwards  wheel  2139989040 12 Nov 13:16 big6
```

**Comment by eteran** [comment]
2GB should definitely work pretty well, so I'm glad that your tests sound like they confirmed it.

Honestly, the primary limitation left in nedit-ng is that It's scroll bars are 32-bit, so a degenerate case of a file that has like 5 billion newlines will break.

So the be conservative, we limit the size of the file that can be opened to 32-bit
