### ISSUE TITLE
default line number background color is too dark

### ISSUE THREAD

**Issue by tksoh** [eteran/nedit-ng#197]
Just a minor observation. 

The line number pane has a default color of nearly black color (1st screenshot). I feel it should be set to the same white color as the text area (like the old nedit), or at least some other light color like #EEEEEE (2nd screenshot)

![2020-12-12 12_07_31-Window](https://user-images.githubusercontent.com/494222/101973392-ba08a880-3c72-11eb-812b-04c0cf247e3a.jpg)

Sample using "#EEEEEE" color

![2020-12-12 12_11_26-Window](https://user-images.githubusercontent.com/494222/101973457-47e49380-3c73-11eb-8657-c7ca5ba0574e.jpg)

**Comment by eteran** [comment]
Heh, not sure I'd consider it a bug since it's a matter of preference I guess. I kinda like it so dark :-P. 

But... I do have plans for even more advanced full app theming at some point. I think the bottom line is, I'll take it under consideration, but given that you can change it so easily if your preference differs from mine, it's not top of my list :-).

**Comment by tksoh** [comment]
I probably wouldn't call it a bug either, especially since nedit doesn't even provide that field in the color dialog. But if the initial goal is to clone old nedit's look and feel, and perhaps make those users at home with nedit-ng, then making both of them with similar appearance would help :-)

**Comment by tksoh** [comment]
I will close the issue, since it's not one technically.

**Comment by eteran** [comment]
I gotcha. I will certainly give some thought to making it lighter like nedit-5... But no promises ;-).
