### ISSUE TITLE
ubuntu font warning

### ISSUE THREAD

**Issue by marilmanen** [eteran/nedit-ng#258]
I'm getting following warning when starting nedit-ng in my laptop with version 39c11d87.
Warning: NEdit: a variable width font has been specified. This is not supported, and will result in unexpected results
I tried also removing my .config/nedit-ng directory, but I still get the message.

**Comment by eteran** [comment]
Sounds like the font that you are using is not a true fixed-width font. 

This message occurs when the font fails the `fixedPitch()` test.

Perhaps try another font? Or of you REALLY like that font, it's just a warning, you can ignore it without much consequence (so long as you don't ask NG to render any characters which are not the standard width.

**Comment by eteran** [comment]
@marilmanen OK, now NG should default to a system recommended fixed-width font for cases like a fresh config directory (or the setting being otherwise unset).

Considering that the UI only offers fixed-width fonts, making only manual manipulation of the config the only real way to end up with a variable-width font now, I think that should close this issue, but as always feel free to re-open if there is a further concern.
