### ISSUE TITLE
poor legibility of selected text

### ISSUE THREAD

**Issue by tksoh** [eteran/nedit-ng#259]
Nedit 5 merely turn the background of selected text into gray color, while preserving the original foreground color of the text. But in NG. the foreground of selected text all gets turned into white color, making it extremely difficult to read for meaningful purpose, especially when in larger, multi-line selection.

I noticed that Qt Creator is having the same behavior. Hopefully this is not a Qt policy :-(

Thankfully, the background color of range-sets do not have this issue.

![2021-01-10 11_31_19-toshiba (tksoh-Satellite-L645_1 (tksoh)) - VNC Viewer](https://user-images.githubusercontent.com/494222/104113743-7bc8dc80-5337-11eb-94c2-91b8383cedcf.jpg)

**Comment by eteran** [comment]
So there are two things at play.

1. I think that the highlight colors are configurable in the Colors' dialog as "Selection foreground" and "Selection background"
2. You can enable the classic highlight coloring behavior in NG! Just set in the `config.ini`, `nedit.colorizeHighlightedText=true`

I can say that **personally**, I find it much more readable to have a single flat color over a highlighted background color and have observed that it is what many editors do. This is why I have this default as such. But, like I said, with the given settings, you can adjust it as needed.

I'm unsure, but I may close this bug since it's not really "broken", so much as it is a question of preferred defaults since the original behavior is available via a setting.

**Comment by tksoh** [comment]
Glad to know there's already a provision.

Once again, without sounding too much like a broken record ;-), to smooth the transition from nedit 5 to 6, I think it should be more prudent to carry forward nedit's original behavior/appearance, cosmetic or otherwise, as much as possible. So I'd like to recommend to make nedit.colorizeHighlightedText=true as default, and let users decide if they want the different way (probably because they come from other editors that do this and would like to keep it that way -- same thing applies to nedit 5 users ;-)

Perhaps more importantly, the syntax highlighting feature exists for the primary purpose of improving legibility, I don't really see how that purpose should become invalid when text are selected.

**Comment by eteran** [comment]
I hear ya, it's a tough decision when it comes to color schemes. NG tries to at the very least, provide a modern look and feel, so part of that is defaulting to the system color palette.

While highlighted text reads well enough on a greyish background, I found it bordering on illegible when the "modern" bright blue default background.

You may be right that for 6.0, we should just stick to "like nedit 5.x" when possible though. So I'll change the default. But truth be told, there's a good chance I'll want to change it back after the preference system is revamped and it makes more sense to have all of these hidden options more accessible in the UI.
