### ISSUE TITLE
compiler warnings when building on Windows 10 with MSVC 2017

### ISSUE THREAD

**Issue by tksoh** [eteran/nedit-ng#297]
Not sure this matter much, but I have been getting a few warnings when building on Windows 10 with MSVC 2017. They are probably harmless.

Full build log attached below. Using commit 9e9acf13b028d86a5a9951b3534a5a71bcad6d7c. Linux build is clean.

[nedit-ng-MSVC2017-build-log.txt](https://github.com/eteran/nedit-ng/files/5886353/nedit-ng-MSVC2017-build-log.txt)
[nedit-ng-linux-build-log.txt](https://github.com/eteran/nedit-ng/files/5886354/nedit-ng-linux-build-log.txt)

**Comment by eteran** [comment]
Thanks for the ticket. I'm going to close this issue though just because I'm aware of the aggressive warnings that msvc issues. 

Over time, I will of course make efforts to reduce them, ideally to zero. But for now, they don't seem to be hurting any functionality as they are mostly about conversions between 64-bit and 32-bit types, but the actual values are currently artificially constrained to what would fit in 32-bits anyway.
