### ISSUE TITLE
make incremental backup trigger threshold customizable 

### ISSUE THREAD

**Issue by tksoh** [eteran/nedit-ng#300]
From nedit help doc (Crash Recovery)

>  NEdit-ng maintains a backup file which it updates periodically (every 8 editing operations or 80 characters typed). 

For me, 80 character is slightly too large (some might find it too little). I'd like be able to customize those settings, so we can adjust the 'risk' level to minimize the impact.

On a related topic, I wonder if nedit could also do the incremental backup by time interval, or over a period of 'idling' time.

**Comment by grege2** [comment]
Great proposal. The fixed 8/80 settings always seemed very hard-wired.  I'd also love say a 5 minute save interval. And while we're here, I'd love a trail of backups, filename.hhmmss, so I could go back say 30 or 60 minutes to a version I know was working. (This is to protect against the user's coding mistakes. Eg, a global case-insensitive Find/Replace that went oh-so-wrong, because there were hundreds of instances of oldThing and oldthing and tempOldThing that you just forgot about.)

**Comment by eteran** [comment]
Good idea, I'll take a look at the plumbing for this and see what we can do. I like the idea of having a time-based option too.

**Comment by eteran** [comment]
Configuring of this setting is implemented!

```
nedit.autoSaveCharLimit
nedit.autoSaveOpLimit
```

are now supported in your `config.ini` file 👍🏻 

I think time-based backup is a post 6.0 feature, but I like it!
