### ISSUE TITLE
Non-UI preferences should not be saved, breaking nc autostart

### ISSUE THREAD

**Issue by sjtringali** [eteran/nedit-ng#320]
Here's a bug that took me a while to figure out.

I use "svrname" to run a bunch of different servers all with constantly changing names, it allows me a separate out a bunch of different code areas.

One day, I changed something like a color, hit Save, and suddently I couldn't use the server anymore. Turns out that nedit would use the server name from whenever I happened to save it, and now nc wouldn't start anymore, because it was looking for a server that never would exist.

Preferences that only were accessible via X resources should not be saved.

**Comment by eteran** [comment]
Interesting, OK, i'll make a quick fix for this!

**Comment by eteran** [comment]
So this is a SLIGHTLY more complex problem than I originally thought, but only because when porting, I decided to have both server and regular settings in a single .ini file.

Basically, the complexity is that when writing the settings, it writes a whole new file every time, so if I simply "don't save" the `serverName`, then it will effectively get erased from the config!

So there's a couple of options I'm considering:

1. Just migrate the server-oriented settings to their own file, something like `$HOME/.config/nedit-ng/server.ini`, which would basically be a read-only setting file shared by `nc` and `nedit`.

2. I could read the current settings right before writing, guaranteeing that I write back what's already in the file

3.  I could manage the settings set at runtime as "overrides" separately and manage what's in the file vs what was set with things like flags (least favorite option).

So I'm going to do some minor experiments to see what makes the most sense to fix this issue.

**Comment by eteran** [comment]
I believe this should be fixed now in the master branch, thanks for the report! Please re-open if you continue to have this issue.

**Comment by sjtringali** [comment]
I think it’s OK if it never saves. Preferences without a UI never were saved and only loaded.

Having the override would help, but I think the mistake is saving state that has no UI.

**Comment by eteran** [comment]
@sjtringali So the fix in master is essentially what I called option 3.

It will load the servername from the config file, and write it back when saving the config.ini. if you use `-svrname` that overrides whats in the config... but will NOT change what's in the config.ini. I think that's the desired behavior.
