### ISSUE TITLE
long -svrname argument

### ISSUE THREAD

**Issue by marilmanen** [eteran/nedit-ng#328]
There seems to be some limitation for the length of the -svrname argument

nc-ng -svrname 01234567890123456789012345678901234567890123 -noask /tmp/x
Warning: NEdit: server failed to start:  "QLocalServer::listen: Name error"

and this causes that the /tmp/x file will not be opened.
I tested also with old nedit and it doesn't have any issue with long names.

**Comment by eteran** [comment]
Interesting. NG uses a different mechanism and creates a local socket for nc <-> nedit communication. Maybe there's a limitation there. I'll look into it, but depending on what the underlying issue is, it may be a limitation we choose to accept (and warn the user about more clearly).

**Comment by eteran** [comment]
One thing that occurred to me, is that the length issue is due to it currently using the string literally given as part of the local socket path in the file system. I think it would be completely reasonable to just hash whatever string the user species and use that.

I don't think it matters what the actual filename is, so long as same svrname == same file. So I think I'll just do that!

**Comment by eteran** [comment]
@marilmanen I believe that the above commit should fix this issue. Please let me know if you run into any problems :-)
