### ISSUE TITLE
Window size does not display on resize

### ISSUE THREAD

**Issue by jabuzz** [eteran/nedit-ng#44]
Running 2018.4 on Ubuntu 18.04 (under Gnome) and when I resize the window it does not display the size of the window as I do so. Works just fine for plain nedit, and the Gnome terminal does it as well. Kind of annoying really as you can't tell how big the window (in terms of characters) you are typing into actually is. It's the only thing stopping me uninstalling nedit and switching to nedit-ng completely.

**Comment by eteran** [comment]
Interesting. I've seen some apps have that feature before, but never have seen nedit have it ...I always figured it was a WM thing!

Either way, I like this feature when it's there, so I'll look into working it in there.

**Comment by eteran** [comment]
Oh, thanks for the hint! I'll look into that ASAP

**Comment by eteran** [comment]
OK, using the size hints is a bit of a rat's nest of complexity because the WM uses the size of the main window (not the text widget) and it's non-trivial to tell X11 via Qt what the "size increment" is, but to exclude the window frame size.

So, I've copied the solution that Konsole uses (which is to manually display the size on the widget for a second). You can enable this by adding the following to the config.ini file (`~/.config/nedit-ng/config.ini`):

`nedit.showResizeNotification = true`

Please re-open the issue if this proves to be insufficient.

**Comment by eteran** [comment]
(Also, as a bonus, with this solution, it will display the size of each pane if multiple panes are open!

**Comment by jabuzz** [comment]
That works great, thanks. The only minor (and it is really rather minor) annoyance is that it displays the size at startup, which is unnecessary because it always 80x25.

**Comment by eteran** [comment]
Ok, I can look I to suppressing it when it's a new window. I do t think that'll be too hard.
