### ISSUE TITLE
How does one import old nedit.rc into nedit-ng?

### ISSUE THREAD

**Issue by elwyos** [eteran/nedit-ng#69]
I have a lot of highlight rules that I'm currently using on classic NEdit.

How does one import the old nedit.rc into the new nedit-ng? I might actually just write a script to export the regexes etc, but was wondering if there's an easier way I'm not aware of.

(searching the code base doesn't seem to show any result related to "nedit.rc" that's up-to-date, but I might be wrong)

**Comment by anjohnson** [comment]
There is a `nedit-import` program that gets built with nedit-ng, although in my case it unfortunately doesn't like the version number that's in my nedit.rc file so I don't know how well it actually works:
```
tux% nedit-import ~/.nedit-home/nedit.rc
Importing is only supported for NEdit 5.6 and 5.7
tux% grep nedit.fileVersion ~/.nedit-home/nedit.rc
nedit.fileVersion: 5.5
```

**Comment by eteran** [comment]
The main reason for the version requiment is because nedit classic had changes to it's regex engine over time, which were dealt with by automagically tweaking them on load.

The import utility doesn't do that, it just copies the rules directly, so it in essence, just assumes they are all up to date.

Thanks @anjohnson for answering the question!
