### ISSUE TITLE
Possibility of multiple font support?

### ISSUE THREAD

**Issue by elwyos** [eteran/nedit-ng#70]
So I've been checking out nedit-ng and noticed that right now it only supports one kind of font. Is it possible for the underlying text display UI component (whatever Qt uses) to support multiple types of fonts in a single line?

I have a feeling that multiple font support is a rarity in text editors.

This is what my NEdit looks like right now : https://cdn.discordapp.com/attachments/480762656689618954/500303132153217045/image0.jpg

(edit: not sure if I'm supposed to tag this post as a discussion, as it's less of an issue and more of a question)

**Comment by eteran** [comment]
Ah, so multiple fonts was actually a feature that I had cut out...

It certainly is/was doable, and there is a version of nedit-ng in the past that did support it as a "legacy feature"... but frankly I wasn't aware that anyone actually used it. It seems like it was added to nedit in order enable the help system to have more rich text.

So to answer your questions:

yes, it is possible
yes, it is rare in code editors to support completely rich text
I don't think it is a feature that I'm likely to re-add, addI removed it in order to vastly simplify the rendering code... but never say never I suppose.
