### ISSUE TITLE
CMake Error: AutoUic (nc-ng): The uic executable "" does not exist

### ISSUE THREAD

**Issue by HJarausch** [eteran/nedit-ng#72]
Hi,
I'm trying to build NEdit-NG on my Gentoo system.
I'm using cmake-3.13.0_rc1  and gcc-8.2.0

cmake fails with
CMake Error: AutoUic (nc-ng): The uic executable "" does not exist

What am I missing?
Many thanks for a hint,
Helmut

**Comment by eteran** [comment]
I'm a gentoo user too. Looks like you are missing perhaps some of the Qt packages.

```
$ equery b /usr/lib/qt5/bin/uic 
 * Searching for /usr/lib/qt5/bin/uic ... 
dev-qt/qtwidgets-5.11.1 (/usr/lib64/qt5/bin/uic)
```

I'm going to close this, please reopen if this continues to be an issue.

Also, consider using the ebuild I host here in my gentoo-overlay: https://github.com/eteran/gentoo-overlay/

**Comment by eteran** [comment]
Also, for the record, the dependencies that I **think** cover all the needs are:

	>=dev-qt/qtgui-5.4.0
	>=dev-qt/qtcore-5.4.0
	>=dev-qt/qtnetwork-5.4.0
	>=dev-qt/qtxml-5.4.0
	>=dev-libs/boost-1.35
	>=sys-devel/bison-3.0

**Comment by mmorandi** [comment]
I was hit by this but too. It's because of [this](https://gitlab.kitware.com/cmake/cmake/merge_requests/2667) cmake bug. As noted by HJaraush the following patch fixes it:

diff --git a/client/CMakeLists.txt b/client/CMakeLists.txt
index f619c4d0..6f8b94be 100644
--- a/client/CMakeLists.txt
+++ b/client/CMakeLists.txt
@@ -2,7 +2,7 @@ cmake_minimum_required(VERSION 3.0)
 
 set(CMAKE_INCLUDE_CURRENT_DIR ON)
 set(CMAKE_AUTOMOC ON)
-set(CMAKE_AUTOUIC ON)
+set(CMAKE_AUTOUIC OFF)
 set(CMAKE_AUTORCC ON)
 
 find_package(Qt5 5.5.0 REQUIRED Core Network)
diff --git a/import/CMakeLists.txt b/import/CMakeLists.txt
index 97de229d..4c657f55 100644
--- a/import/CMakeLists.txt
+++ b/import/CMakeLists.txt
@@ -2,7 +2,7 @@ cmake_minimum_required(VERSION 3.0)
 
 set(CMAKE_INCLUDE_CURRENT_DIR ON)
 set(CMAKE_AUTOMOC ON)
-set(CMAKE_AUTOUIC ON)
+set(CMAKE_AUTOUIC OFF)
 set(CMAKE_AUTORCC ON)
 
 find_package(Qt5 5.5.0 REQUIRED Core Xml)

**Comment by eteran** [comment]
Thanks for the follow up! I think neither of those modules acquire UIC, so I'll probably apply that patch tonight 👍
