### ISSUE TITLE
Windows Split Pane Horizontal

### ISSUE THREAD

**Issue by marilmanen** [eteran/nedit-ng#96]
Could you add support for horizontal split of the window (maybe Shift+Ctrl+2)? I tested it by adding `splitter_->setOrientation(Qt::Horizontal);` to `DocumentWidget::splitPane` and it seems to be working fine.

**Comment by eteran** [comment]
Great idea, monitors are wider than they used to be, a horizontal split makes a lot of sense.

Yes, that is exactly how it would be done, I'll look into exactly how this should be implemented from a usability perspective. I'm not sure a Shift shortcut works well though, because the splitter can only have one orientation at a time... but a user might think they could.

I am thinking perhaps an advanced option in the config file.

**Comment by eteran** [comment]
Implemented in latest push!

It is currently controlled by an advanced setting in the config.ini

    nedit.splitHorizontally=true

that should cause the splits to be horizontal instead of vertical. I will think about ways to offer more advanced options (like maybe changing the orientation of the split on a per-tab basis). But this gets the core feature in for now.

**Comment by marilmanen** [comment]
Great, this is enough for me at the moment.
A "line number alignment" with the horizontal split would also be a nice optional feature i.e. a single vertical scroll bar even when horizontal split is used.
Ultimate target could be to support simultaneous vertical and horizontal split in all tabs with the possibility to change orientations.

**Comment by eteran** [comment]
Totally!

I am thinking maybe a menu/shortcut to swap the orientation of the split for a given tab should be easy to implement :-)
